name: dyvolt_employee
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
dependencies:
  animations: ^2.0.7
  blur: ^3.1.0
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_blurhash: ^0.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.7
  flutter_time_picker_spinner: ^2.0.0
  intl: ^0.18.1
  rive: ^0.11.4
  time_picker_spinner_pop_up: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/izin/
    - assets/images/izin/sakit/
    - assets/images/izin/kerja/
    - assets/images/order/
    - assets/images/payment/
    - assets/images/ornaments/
    - assets/images/promo/
    - assets/animations/
  uses-material-design: true
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dyvolt_app_icon.png"
  adaptive_icon_background: "#2051E5"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/dyvolt_app_icon.png"
    background_color: "#2051E5"
    theme_color: "#2051E5"
  windows:
    generate: true
    image_path: "assets/images/dyvolt_app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/dyvolt_app_icon.png"
  linux:
    generate: true
    image_path: "assets/images/dyvolt_app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
